name: 🚀 Onboarding to GitHub Actions
description: Answer the questions for a generated template to onboard onto GitHub Actions using our pre-created reusable workflows
title: "🚀 Onboarding to GitHub Actions"
labels: ["actions"]
body:
  - type: input
    attributes:
      label: Business Unit
      description: Enter in the name of the business unit/team
      placeholder: finance-it
    validations:
      required: true
  - type: textarea
    attributes:
      label: Repositories
      description: Enter in the name of the repository name, 1 per line, in the format of ORG-NAME/REPO-NAME
      placeholder: | 
        joshjohanning-org/my-repo-name
        joshjohanning-org/my-other-repo-name
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Repo Language
      description: Please select the visibility for the new repository
      options:
        - PLEASE SELECT ONE
        - docker (not implemented yet)
        - java
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Other Configuration
      description: Add in these other configuration files / workflows into the repository? 
      options:
        - label: "Dependency Review workflow (not implemented yet)"
          required: false
        - label: "Dependabot configuration"
          required: false
        - label: "CodeQL advanced workflow (not implemented yet)"
          required: false
