name: 🚀 Onboarding to GitHub Actions
description: Answer the questions for a generated template to onboard onto GitHub Actions using our pre-created reusable workflows
title: "🚀 Onboarding to GitHub Actions"
labels: ["actions"]
body:
  - type: input
    attributes:
      label: Repo Name
      description: Enter in the name of the repository in GitHub in the format of ORG-NAME/REPO-NAME
      placeholder: joshjohanning-org/my-repo-name
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Repo Language
      description: Please select the visibility for the new repository
      options:
        - docker
        - terraform
        - java (todo)
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Other Configuration
      description: Add in these other configuration files / workflows into the repository? 
      options:
        - label: "Dependency Review"
          required: false
        - label: "Dependabot"
          required: false
